app/account/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.shortcuts import render, redirect
from django.urls import reverse


app_name = 'account'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password/', views.PasswordResetView.as_view(), name='password-reset'),

    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('addresses/', views.AddressesView.as_view(), name='addresses'),

    path('addresses/', views.AddressesView.as_view(), name='addresses'),
    path('delete-address/<int:id>/', views.delete_address, name='delete-address'),


    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('terms-conditions/', views.termsandservices, name='terms'),
]

app/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
]

app/website/models.py
from django.db import models
from django.dispatch import receiver

# Create your models here.
class Components(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    hierarchy_level = models.IntegerField()
    parent_id = models.ForeignKey('self', 
                                  blank=True, null=True,
                                  on_delete=models.SET_NULL, db_column= 'parent_id')
    parent_name = models.CharField(max_length=100, blank=True, null=True, editable=False)
    date_deleted = models.DateField(blank=True,null=True)
    value = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Components'

@receiver(models.signals.pre_save, sender=Components, weak=False)
def components_choices(sender, instance, **kwargs):
    if not instance.parent_id:
        return False
    instance.parent_name = sender.objects.get(name=instance.parent_id).name


class EmailComponent(models.Model):
    id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length = 254)
    phone = models.CharField(max_length=12)
    subject = models.CharField(max_length = 70)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)
    
    class Meta:
        verbose_name_plural = 'Email Components'

app/website/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import CharField, TextInput, EmailInput, EmailField, Textarea
from .models import EmailComponent


class ContactEmailForm(forms.ModelForm):

    error_messages = {
        'subject_require': ("Subject is required"),
        'message_empty': ("Your message is empty"),
    }
    
    first_name = CharField(widget=TextInput(attrs={'class': 'form-control'}))
    last_name = CharField(widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(required=True,
                        max_length=254,
                        help_text='Required. Inform a valid email address.', 
                        widget=EmailInput(attrs={'class': 'form-control'}))
    phone = CharField(widget=TextInput(attrs={'class': 'form-control',}))
    subject = CharField(widget=TextInput(attrs={'class': 'form-control'}))
    message = CharField(widget=Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = EmailComponent
        fields = ('first_name','last_name', 'email', 'phone', 'subject', 'message')
    
    def __init__(self, *args, **kwargs):
        super(ContactEmailForm, self).__init__(*args, **kwargs)
        self.fields['phone'].required = True

app/website/views.py
from django.shortcuts import render,  redirect
from django.views import View
from ecommerce.views import get_shop_categories
from ecommerce.cart import Cart
from django.contrib import messages

from .models import Components
from .forms import ContactEmailForm

from django.core.mail import send_mail
from django.template.loader import render_to_string

# Create your views here.
class ContactView(View):
    template = 'contact.html'

    def get(self, request):

        faq = Components.objects.filter(parent_name__contains='Question')

        form = ContactEmailForm()

        context = { 'category' : get_shop_categories(),
                    'cart_length' : Cart(request).__len__(),
                    'faq' : faq,
                    'form' : form
                    }


        return render(request, self.template, context)
    
    def post(self, request):

        faq = Components.objects.filter(parent_name__contains='Question')
        form = ContactEmailForm(request.POST)

        if form.is_valid():
            context = {
                'first_name' : form.cleaned_data.get('first_name'),
                'last_name' : form.cleaned_data.get('last_name'),
                'phone' : form.cleaned_data.get('phone'),
                'email' : form.cleaned_data.get('email'),
                'subject' : form.cleaned_data.get('subject'),
                'message' : form.cleaned_data.get('message')
            }
            message_content = render_to_string('contact-email.txt',context)
            
            send_mail(
                subject = form.cleaned_data.get('subject'),
                message = message_content,
                from_email = None,
                recipient_list= ['vietaodaiboutique@gmail.com'],
                fail_silently= False
            )

            form.save()
            messages.success(request, 'Messages sent successfully', extra_tags='success')            
            return redirect('website:contact')

        else:
            messages.error(request, 'Messages sent error', extra_tags='error')
            context = { 'category' : get_shop_categories(),
                    'cart_length' : Cart(request).__len__(),
                    'faq' : faq,
                    'form' : form
                    }

        return render(request, self.template, context)

app/website/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block shop %}
<section class="hero">
    {% if messages %}
    {% for message in messages %}
        {% if "success" in message.tags %}<div class="alert alert-success text-center">{{ message }}</div>{% endif %}
        {% if "error" in message.tags %}<div class="alert alert-danger text-center">{{ message }}</div>{% endif %}
    {% endfor %}
    {% endif %}
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-6">
                <h1 class="font-weight-light">
                    <b class="d-block">Get in touch!</b>
                    (By Appointment Only)
                    <br>
                    Open from 10am - 7pm.
            </h1>
            </div>
        </div>
        <div class="row gutter-4">
            <div class="col-md-5 col-lg-4">
                <span class="eyebrow">Our location</span>
                <p class="lead my-1 text-dark">
                    Fairfax, VA 22030
                    <br>
                    +01 703 687 7879
                </p>
            </div>
            <div class="col-md-5 col-lg-4">
                <span class="eyebrow">Contact Us</span>
                <p class="lead my-1 text-dark">
                    Phone: +01 703 687 7879
                </p>
                <a href="mailto: vietaodaiboutique@gmail.com" class="eyebrow underline action">vietaodaiboutique@gmail.com</a>
            </div>
        </div>
    </div>
</section>
<section class="bg-light">
    <div class="container">
        <div class="row gutter-2 gutter-md-4">
            <div class="col-md-4 col-lg-3">
                <h2 class="h3 mb-4 mb-mb-0">FAQ</h2>
            </div>
            <div class="col-md-8 col-lg-9">
                <div class="accordion accordion-minimal" id="accordion-1">
                    {% for q in faq %}
                    <div class="card">
                        <div class="card-header" id="heading-1-{{ forloop.counter }}">
                            <h2 class="mb-0">
                                <button class="btn btn-link"
                                        type="button"
                                        data-toggle="collapse"
                                        data-target="#collapse-1-{{ forloop.counter }}"
                                        aria-expanded="false"
                                        aria-controls="collapse-1-{{ forloop.counter }}">
                                    {{ q.parent_id.value }}
                                </button>
                            </h2>
                        </div>
                        <div id="collapse-1-{{ forloop.counter }}"
                             class="collapse"
                             aria-labelledby="heading-1-{{ forloop.counter }}"
                             data-parent="#accordion-1">
                            <div class="card-body">
                                <p>
                                    {{ q.value}}
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container">

        <div class="row gutter-4">
            <div class="col-lg-4">
                <h2 class="font-weight-light">
                    <b>Send us an email</b>
                </h2>
                <p>
                    We don't spam. Promise!
                </p>
            </div>
        
            <div class="col-lg-8 pl-lg-5">
                <form method="post" id="ContactForm">{% csrf_token %}
                <div class="row gutter-2">
                    
                        <div class="form-group col-md-6">
                            <label for="id_first_name">First Name</label>
                            {{ form.first_name }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.first_name.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_last_name">Last Name</label>
                            {{ form.last_name }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.last_name.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="form-group col-12">
                            <label for="id_email">Email</label>
                            {{ form.email }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.email.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="form-group col-12">
                            <label for="id_phone">Phone Number</label>
                            {{ form.phone }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.phone.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="form-group col-12">
                            <label for="id_subject">Subject</label>
                            {{ form.subject }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.subject.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="form-group col-12">
                            <label for="id_message">Message</label>
                            {{ form.message }}
                            <ul class="list-group list-group-item-danger">
                                {% for i in form.message.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                            </ul>
                        </div>
                        <div class="col-3 mt-2">
                            <input type="submit" name="Send" value="Send Messages" class="btn btn-block btn-dark">
                        </div>
                    
                </div>
                </form>
            </div>  
        </div>
    </div>
</section>
{% endblock %}