app/account/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.shortcuts import render, redirect
from django.urls import reverse


app_name = 'account'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password/', views.PasswordResetView.as_view(), name='password-reset'),

    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('addresses/', views.AddressesView.as_view(), name='addresses'),

    path('addresses/', views.AddressesView.as_view(), name='addresses'),
    path('delete-address/<int:id>/', views.delete_address, name='delete-address'),


    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('terms-conditions/', views.termsandservices, name='terms'),
]

app/ecommerce/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.shortcuts import render, redirect
from django.urls import reverse


app_name = 'ecommerce'

urlpatterns = [
    path('lookbook/', views.LookbookView.as_view(), name='lookbook'),

    path('checkout/<str:shipping_method>',views.CheckOutView.as_view(),name='checkout'),
    
    path('', views.redirect_home),
    path('shop/', views.ShopView.as_view(), name='shop-all'),
    path('shop/<slug:slug_url>/', views.ShopCategoryView.as_view(), name='shop-category'),

    path('product/<str:slug>/',views.ProductDetailView.as_view(),name='product-detail'),

    path('cart/',views.CartView.as_view(),name='shopping-cart'),

    # path for AJAX
    path('ajax/shop/filter-data/', views.filter_data_all,name='filter-data-all'),
    path('ajax/<slug:slug_url>/filter-data/', views.filter_data_category,name='filter-data'),
    path('ajax/<slug:slug>/color-filter-product/', views.product_color_choice,name='color-filter-data'),
    path('ajax/<slug:slug>/color-size-filter-product/', views.quantity_choice,name='color-filter-data'),

    path('ajax/add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('ajax/delete-from-cart/',views.delete_from_cart,name='delete-from-cart'),
    path('ajax/update-cart/',views.update_cart,name='update_cart'),

]

app/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/account/models.py
from django.db import models
from django.conf import settings
import uuid
from django.db.models import Q
import datetime
from django.dispatch import receiver

from ecommerce.models import Attribute
from django.contrib.auth.models import User


class Customer(models.Model):
    id = models.BigAutoField(editable=False, primary_key=True, unique=True)
    customer_uuid = models.UUIDField(default=uuid.uuid4, 
                                    editable=False, 
                                    unique=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(max_length = 254)
    is_subcribe_email = models.BooleanField(default=True)
    is_signup_user = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            blank=True, null=True,
                            on_delete=models.SET_NULL,
                            )
    date_joined = models.DateTimeField(auto_now_add=True)
    date_deleted = models.DateTimeField(blank=True,null=True)
   
    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name_plural = 'Customers'


@receiver(models.signals.pre_save, sender=Customer, weak=False)
def user_receiver(sender, instance, *args, **kwargs):
    try:
        userprofile = User.objects.get(username=instance.user)
        if userprofile:
            userprofile.first_name = instance.first_name
            userprofile.last_name = instance.last_name
            userprofile.email = instance.email
            userprofile.username = instance.email
            userprofile.save()
    except User.DoesNotExist:
        pass

@receiver(models.signals.pre_delete, sender=settings.AUTH_USER_MODEL, weak=False)
def set_date_deleted_user(sender, instance, *args, **kwargs):
    try:
        instance = Customer.objects.get(email=instance.email)
        if instance:
            instance.date_deleted = datetime.datetime.now()
            instance.is_signup_user = False
            instance.save()
    except Customer.DoesNotExist:
        pass

class Address(models.Model):
    customer_id = models.ForeignKey(Customer,
                                    on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    address_type = models.ForeignKey(Attribute, 
                              limit_choices_to = Q(date_deleted__isnull=True) &
                                                 Q(parent_name__in=['Address Type']),
                              related_name = 'attribute_address',
                              on_delete=models.CASCADE,blank=True,null=True)
    default = models.BooleanField(default=False)
    date_deleted = models.DateTimeField(blank=True,null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.customer_id.email

    class Meta:
        verbose_name_plural = 'Addresses'

app/account/views.py
from django.shortcuts import  render, redirect
from django.views import View

from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib import messages

from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from django.db.models import Sum

# import pagination
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from .forms import NewUserForm, ProfileCustomerForm, AddressForm, PasswordResetForm
from ecommerce.cart import Cart
from ecommerce.views import get_shop_categories
from .models import Customer, Address
from order.models import OrderItem, OrderStatus, Order

def delete_address(request, id):
    
    obj = get_object_or_404(Address, id = id)

    if request.method =="GET":
        obj.delete()
        return redirect(request.GET.get('next'))

class LoginView(View):
    template_name = 'portal.html'

    def get(self, request):
        form = NewUserForm()
        context = {'form': form, 'cart_length': Cart(request).__len__(), 'category' : get_shop_categories(),}
        return render(request, self.template_name, context)

    def post(self,request):
        if 'Login' in request.POST:
            email = request.POST.get('email')
            password = request.POST.get('password')
            if not email or not password:
                messages.error(request, 'Both email address and password are required.', extra_tags='login')
                return redirect('account:login')
            user_obj = User.objects.filter(email=email).first()
            if user_obj is None:
                messages.error(request, 'User not found.', extra_tags='login')
                return redirect('account:login')
            user = authenticate(username = user_obj.username, password = password)
            if user is not None:
                login(request, user)
                cust_uuid = Customer.objects.get(email=request.user.email).customer_uuid
                request.session['customer'] = str(cust_uuid)
                if not self.request.GET.get('next'):
                    return redirect(reverse('account:profile'))
                else:
                    return redirect(self.request.GET.get('next'))
            else:
                messages.error(request, 'Wrong password', extra_tags='login')
                return redirect('account:login')
        elif 'Register' in request.POST:
            form = NewUserForm(request.POST)
            if form.is_valid():
                newuser = form.save()
                try:
                    cust_profile = Customer.objects.get(email=form.cleaned_data.get('email'))
                    cust_profile.is_signup_user = True
                    cust_profile.save()
                except Customer.DoesNotExist:
                    customer = Customer.objects.create(user=newuser,
                                              first_name=form.cleaned_data.get('first_name'),
                                              last_name=form.cleaned_data.get('last_name'),
                                              is_signup_user=True,
                                              email=form.cleaned_data.get('email'))

                username = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                customer = Customer.objects.get(email=request.user.email)
                request.session['customer'] = str(customer.customer_uuid)
                if not self.request.GET.get('next'):
                    return redirect(reverse('account:profile'))
                else:
                    return redirect(self.request.GET.get('next'))
            else:
                context = {'form': form, 
                            'registration': "active", 
                            'cart_length':  Cart(request).__len__(),
                            'category' : get_shop_categories(),}
                return render(request, self.template_name, context)

def logout_view(request):
    logout(request)
    if not request.GET.get('next'):
        return redirect(reverse('ecommerce:shop-all'))
    else:
        return redirect(request.GET.get('next'))
     

class ProfileView(LoginRequiredMixin, View):
    profile_template = 'profile.html'
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        
        try:
            profile = Customer.objects.get(customer_uuid = request.session['customer'])
        except:
            messages.error(request, 'User not found.', extra_tags='login')
            return redirect('account:login')
        
        form = ProfileCustomerForm(instance = profile)
            
        context = {'profile' :profile,
                    'form':form,
                    'cart_length': Cart(request).__len__(),
                    'category' : get_shop_categories(),}
        return render(request, self.profile_template, context)
    
    def post(self, request):
        
        profile = Customer.objects.get(customer_uuid = request.session['customer'])
        form = ProfileCustomerForm(request.POST, instance= profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Update successfully', extra_tags='success')
            return redirect('account:profile')
        else:
            messages.error(request, 'Unable to update', extra_tags='error')
            context = { 'profile' :profile,
                        'form':form,
                        'cart_length': Cart(request).__len__(),
                        'category' : get_shop_categories(),}
            return render(request, self.profile_template, context)

class PasswordResetView(LoginRequiredMixin, View):
    template = 'password.html'
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        try:
            profile = Customer.objects.get(customer_uuid = request.session['customer'])
        except:
            messages.error(request, 'User not found.', extra_tags='login')
            return redirect('account:login')
        
        if request.user.is_authenticated:
            form = PasswordResetForm(instance=request.user)
            
        context = {'profile' :profile,
                    'form':form,
                    'cart_length': Cart(request).__len__(),
                    'category' : get_shop_categories(),}
        return render(request, self.template, context)

    def post(self,request):
        
        try:
            profile = Customer.objects.get(customer_uuid = request.session['customer'])
        except:
            messages.error(request, 'User not found.', extra_tags='login')
            return redirect('account:login')
        
        
        form = PasswordResetForm(instance=request.user,data=request.POST)

        if form.is_valid():
            user = request.user

            if user.check_password(request.POST.get('oldpassword')):
                form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Update successfully', extra_tags='success')
                return redirect('account:password-reset')
            else:
                messages.error(request, 'You entered a wrong current password', extra_tags='error')
                return redirect('account:password-reset')
        else:
            context = {'profile' :profile,
                    'form':form,
                    'cart_length': Cart(request).__len__(),
                    'category' : get_shop_categories(),}
            return render(request, self.template, context)
    


class OrdersView(LoginRequiredMixin, View):
    template = 'orders.html'
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        
        try:
            profile = Customer.objects.get(customer_uuid = request.session['customer'])
        except:
            messages.error(request, 'User not found.', extra_tags='login')
            return redirect('account:login')
        
        orders = Order.objects.filter(customer_id = profile).order_by('-created_at')
        paginator = Paginator(orders, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


        try:
            order_status = OrderStatus.objects.filter(order_id__in = orders)\
                            .order_by('order_id','-created_at')\
                            .distinct('order_id')
        except:
            order_status = None

        try:
            order_item  = OrderItem.objects.filter(order_id__in = orders)
        except:
            order_status = None

        
            
        context = { 'profile' :profile,
                    'order_status': order_status,
                    'order_item' : order_item,
                    'cart_length': Cart(request).__len__(),
                    'category' : get_shop_categories(),
                    'page_obj' : page_obj}
        return render(request, self.template, context)

class AddressesView(LoginRequiredMixin, View):
    template = 'address.html'
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        
        try:
            profile = Customer.objects.get(customer_uuid = request.session['customer'])
        except:
            messages.error(request, 'User not found.', extra_tags='login')
            return redirect('account:login')
        
        address = Address.objects.filter(customer_id = profile).order_by('-date_created')
        form = AddressForm()
            
        context = { 'form2' : form,

app/order/views.py
from django.shortcuts import render

# Create your views here.

app/account/templates/address.html
{% extends 'base.html' %}
{% load static %}
{% block portal %}
    {% include 'hero-section.html' %}
    <!-- listing -->
    <section>
        <div class="container" style="min-height:50vh">
            <div class="row gutter-4 justify-content-between">
                <aside class="col-lg-3">
                    <div class="sticky-top nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:password-reset' %}">Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'account:addresses' %}">Addresses</a>
                        </li>
                    </div>
                    {% if request.user.is_staff %}
                    <hr>
                    <div class="sticky-top nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:dashboard' %}">Dashboard</a>
                        </li>
                    </div>
                    {% endif %}
                </aside>
                <!-- content -->
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col">
                            <div class="tab-content" id="myTabContent">
                                <!-- addresses -->
                                <div class="tab-pane fade show active"
                                     id="sidebar-1-3"
                                     role="tabpanel"
                                     aria-labelledby="sidebar-1-3">
                                    <div class="row">
                                        <div class="col">
                                            <h3 class="mb-0">Addresses</h3>
                                            <span class="eyebrow">{{ addresses|length }} Entry</span>
                                        </div>
                                    </div>
                                    <div class="row gutter-2">
                                        {% for address in addresses %}
                                            <div class="col-md-6">
                                                <div class="card card-data">
                                                    <div class="card-header card-header-options">
                                                        <div class="row align-items-center">
                                                            <div class="col">
                                                                <h3 class="card-title">
                                                                    Address {{ forloop.counter }}
                                                                    {% if address.default %}- Default{% endif %}
                                                                </h3>
                                                            </div>
                                                            <div class="col text-right">
                                                                <div class="dropdown">
                                                                    <button id="dropdownMenuButton"
                                                                            data-toggle="dropdown"
                                                                            aria-haspopup="true"
                                                                            aria-expanded="false"
                                                                            type="button"
                                                                            class="btn btn-lg btn-secondary btn-ico">
                                                                        <i class="bi-three-dots-vertical"></i>
                                                                    </button>
                                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                                        <li>
                                                                            <a class="dropdown-item" href="#!">Edit</a>
                                                                        </li>
                                                                        <li>
                                                                            <a class="dropdown-item"
                                                                               href="{% url 'account:delete-address' address.id %}?next={{ request.path }}">Delete</a>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="card-body w-75">
                                                        <p class="card-text">
                                                            {{ address.street_address }}
                                                            <br>
                                                            {% if address.apartment_address %}
                                                                {{ address.apartment_address }}
                                                                <br>
                                                            {% endif %}
                                                            {{ address.city }}, {{ address.state }} - {{ address.zip }}
                                                            <br>
                                                            United States
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <h3>New Address</h3>
                                        </div>
                                    </div>
                                    <form method="post" id="ContactInfo">
                                        {% csrf_token %}
                                        <div class="row gutter-1 mb-6" id="AddressForm">
                                            <div class="form-group col-md-12">
                                                <label for="id_street_address">Address</label>
                                                {{ form2.street_address }}
                                                <ul class="list-group list-group-item-danger">
                                                    {% for i in form2.street_address.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                                                </ul>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <label for="id_apartment_address"></label>
                                                {{ form2.apartment_address }}
                                                <ul class="list-group list-group-item-danger">
                                                    {% for i in form2.apartment_address.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                                                </ul>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="id_city">City</label>
                                                {{ form2.city }}
                                                <ul class="list-group list-group-item-danger">
                                                    {% for i in form2.city.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                                                </ul>
                                            </div>
                                            <div class="form-group col-md-3">
                                                <label for="id_state">State</label>
                                                {{ form2.state }}
                                                <ul class="list-group list-group-item-danger">
                                                    {% for i in form2.state.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                                                </ul>
                                            </div>
                                            <div class="form-group col-md-3">
                                                <label for="id_zip">ZIP Code</label>
                                                {{ form2.zip }}
                                                <ul class="list-group list-group-item-danger">
                                                    {% for i in form2.zip.errors %}<li class="list-group-item">{{ i|striptags }}</li>{% endfor %}
                                                </ul>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <label for="id_country">Country</label>
                                                <input type="text"
                                                       name="country"
                                                       class="form-control"
                                                       id="id_country"
                                                       value='United States'
                                                       disabled
                                                       style="background-color: transparent;">
                                            </div>
                                            <div class="col-12">
                                                <div class="custom-control custom-switch mb-2">
                                                    {{ form2.default }}
                                                    <label class="custom-control-label text-muted" for="id_default">Make this a default address</label>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col">
                                                    <input type="submit" value="Add" name="Add" class="btn btn-light">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </section>
                {% endblock %}

app/account/templates/hero-section.html
<!-- hero -->
<section class="hero hero-small text-dark" style="background-color:#FAFAD2">
    <div class="container pt-3">
        <div class="row gutter-2 gutter-md-4 align-items-end">
            <div class="col-md-6 text-center text-md-left">
                <h1 class="mb-0">{{profile.first_name }} {{ profile.last_name }}</h1>
                <span class="text-muted">{{profile.email }}</span>
            </div>
        </div>
    </div>
</section>