app/account/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.shortcuts import render, redirect
from django.urls import reverse


app_name = 'account'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password/', views.PasswordResetView.as_view(), name='password-reset'),

    path('orders/', views.OrdersView.as_view(), name='orders'),
    path('addresses/', views.AddressesView.as_view(), name='addresses'),

    path('addresses/', views.AddressesView.as_view(), name='addresses'),
    path('delete-address/<int:id>/', views.delete_address, name='delete-address'),


    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('terms-conditions/', views.termsandservices, name='terms'),
]

app/ecommerce/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.shortcuts import render, redirect
from django.urls import reverse


app_name = 'ecommerce'

urlpatterns = [
    path('lookbook/', views.LookbookView.as_view(), name='lookbook'),

    path('checkout/<str:shipping_method>',views.CheckOutView.as_view(),name='checkout'),
    
    path('', views.redirect_home),
    path('shop/', views.ShopView.as_view(), name='shop-all'),
    path('shop/<slug:slug_url>/', views.ShopCategoryView.as_view(), name='shop-category'),

    path('product/<str:slug>/',views.ProductDetailView.as_view(),name='product-detail'),

    path('cart/',views.CartView.as_view(),name='shopping-cart'),

    # path for AJAX
    path('ajax/shop/filter-data/', views.filter_data_all,name='filter-data-all'),
    path('ajax/<slug:slug_url>/filter-data/', views.filter_data_category,name='filter-data'),
    path('ajax/<slug:slug>/color-filter-product/', views.product_color_choice,name='color-filter-data'),
    path('ajax/<slug:slug>/color-size-filter-product/', views.quantity_choice,name='color-filter-data'),

    path('ajax/add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('ajax/delete-from-cart/',views.delete_from_cart,name='delete-from-cart'),
    path('ajax/update-cart/',views.update_cart,name='update_cart'),

]

app/main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
]

app/ecommerce/views.py
from django.shortcuts import render, redirect

from .models import Category, Item, Attribute,ItemsInventory,ItemsImage
from django.http import JsonResponse, Http404
from django.template.loader import render_to_string
from django.views import View
from django.shortcuts import get_object_or_404
from django.urls import reverse

from django.contrib import messages
from django.db.models import Max, Q

import os
from django.core.mail import send_mail, EmailMultiAlternatives
from email.mime.image import MIMEImage
from django.conf import settings

from .cart import Cart
from account.models import Customer, Address
from order.models import Order, OrderItem, OrderStatus
# import pagination
from django.core.paginator import Paginator
from account.forms import AnonymousCustomerForm, AddressForm

def redirect_home(request):
    return redirect(reverse('ecommerce:shop-all'))

class CheckOutView(View):
    template_pickup = 'checkout-pickup.html'
    template_ship = 'checkout-ship.html'
    template_confirmation = 'order-confirmation.html'
    
    attr = Attribute.objects.all()

    def get(self, request, shipping_method):
        if request.user.is_authenticated:
            customer = Customer.objects.get(email=request.user.email)
            form = AnonymousCustomerForm(instance=customer)
            try: 
                address = Address.objects.filter(customer_id=customer, default=True).latest('date_created')
                form2 = AddressForm(instance = address)
            except Address.DoesNotExist:
                form2 = AddressForm()
        else: 
            form = AnonymousCustomerForm()
            form2 = AddressForm()
                
        cart = Cart(request)
        SKU = [i['product'] for i in cart]
        ordered_item = ItemsInventory.objects.filter(SKU__in = SKU)

        context = {'ordered_items' : ordered_item,
                    'cart_length' : cart.__len__(),
                    'cart' : cart,
                    'category' : get_shop_categories(),
                    }

        if shipping_method == 'pickup':
            context['form'] = form
            context['sub_total'] = round(cart.get_total_price(),2)
            context['total'] = round(cart.get_total_price(),2)
            return render(request, self.template_pickup, context)
        elif shipping_method == 'shiptohome':
            context['form'] = form
            context['form2'] = form2
            context['ship_cost'] = float(self.attr.get(parent_name='Shipping Cost').name)
            context['sub_total'] = round(cart.get_total_price(),2)
            context['total'] = round(cart.get_total_price(),2) + float(self.attr.get(parent_name='Shipping Cost').name)
            return render(request, self.template_ship, context)
        else:
            raise Http404('Page not found')

    def post(self, request, shipping_method):
        
        cart = Cart(request).__dict__.get('cart')
        if cart.__len__() == 0:
            messages.error(request, "Nothing in your cart",extra_tags='outofstock')
            return redirect(reverse('ecommerce:checkout',args=[shipping_method])) 

        try:
            customer = Customer.objects.get(email=request.POST.get('email'))
            form = AnonymousCustomerForm(request.POST, instance = customer)
        except Customer.DoesNotExist:
            form = AnonymousCustomerForm(request.POST)

        # Validation to check if items still available
        ordered_item = ItemsInventory.objects.filter(SKU__in = list(cart.keys()))
        for i in ordered_item:
            for j in cart:
                if i.SKU == j:
                    if cart[j].get('qty') > i.quantity:
                        messages.error(request, "Checkout error, '{0}' more than our inventory".format(i.item_id.title)
                                        ,extra_tags='outofstock')
                        return redirect(reverse('ecommerce:checkout',args=[shipping_method])) 
        if form.is_valid():
                form.save()
                customer = Customer.objects.get(email=form.cleaned_data.get('email'))
        
        if shipping_method == 'pickup':
            order_type_value=self.attr.get(name=shipping_method)
            new_order  = Order.objects.create(customer_id=customer,
                                                    discount_amount = 0,
                                                    order_type = order_type_value,
                                                    shipping_price = float(request.POST.get('shipcost')),
                                                    subtotal = float(request.POST.get('subtotal')),
                                                    undiscounted_total = float(request.POST.get('subtotal')),
                                                    total_net = float(request.POST.get('totalnet')),
                                                    created_by = form.cleaned_data.get('email')
                                                    )
            
            
            default_status = self.attr.get(name='Received')
            OrderStatus.objects.create(order_id=new_order,
                                        status = default_status,
                                        created_by = form.cleaned_data.get('email')
                                        )
            for i in cart:
                SKU = ordered_item.get(SKU=i)
                OrderItem.objects.create(order_id=new_order,
                                        SKU = SKU,
                                        quantity = cart[i].get('qty')
                                        )
            Cart(request).clear()
        else:
            try:
                child = Address.objects.get(customer_id=customer,
                                            street_address=str(request.POST.get('street_address')),
                                            apartment_address=str(request.POST.get('apartment_address')),
                                            city=str(request.POST.get('city')),
                                            state=str(request.POST.get('state')),
                                            zip=str(request.POST.get('zip'))
                                            )
                if request.user.is_authenticated and request.POST.get('default') == 'on':
                    if not child.default:
                        try:
                            unsaved_address = Address.objects.get(customer_id=customer,default=True)
                            unsaved_address.default = False
                            unsaved_address.save()
                        except Address.DoesNotExist:
                            pass
                        child.default = True
                        child.save()                   
            except Address.DoesNotExist:
                if request.user.is_authenticated and request.POST.get('default') == 'on':
                    try:
                        unsaved_address = Address.objects.get(customer_id=customer,default=True)
                        unsaved_address.default = False
                        unsaved_address.save()
                    except Address.DoesNotExist:
                        pass
                    form2 = AddressForm(request.POST)
                    if form2.is_valid():
                        child = form2.save(commit=False)
                        child.customer_id = customer
                        child.save()
                elif request.user.is_authenticated and not request.POST.get('default'):
                    form2 = AddressForm(request.POST)
                    if form2.is_valid():
                        child = form2.save(commit=False)
                        child.customer_id = customer
                        child.save()
                else:
                    form2 = AddressForm(request.POST)
                    if form2.is_valid():
                        child = form2.save(commit=False)
                        child.customer_id = customer
                        child.save()
            
                
            order_type_value=self.attr.get(name=shipping_method)
            new_order  = Order.objects.create(customer_id=customer,
                                                    discount_amount = 0,
                                                    order_type = order_type_value,
                                                    shipping_address = child,
                                                    shipping_price = float(request.POST.get('shipcost')),
                                                    subtotal = float(request.POST.get('subtotal')),
                                                    undiscounted_total = float(request.POST.get('subtotal')),
                                                    total_net = float(request.POST.get('totalnet')),
                                                    created_by = form.cleaned_data.get('email')
                                                    )
            default_status = self.attr.get(name='Received')
            OrderStatus.objects.create(order_id=new_order,
                                        status = default_status,
                                        created_by = form.cleaned_data.get('email')
                                        )
            for i in cart:
                SKU = ordered_item.get(SKU=i)
                OrderItem.objects.create(order_id=new_order,
                                        SKU = SKU,
                                        quantity = cart[i].get('qty')
                                        )
            Cart(request).clear()
        
        order_items = OrderItem.objects.filter(order_id = new_order)

        context = { 'cart_length' : Cart(request).__len__(),
                    'cart' : Cart(request),
                    'category' : get_shop_categories(),
                    'order_ref_id' : new_order,

app/ecommerce/templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, height=device-height, initial-scale=1, shrink-to-fit=no, user-scalable=no">
        <link rel="stylesheet" href="{% static '/assets/css/vendor.css' %}" />
        <link rel="stylesheet" href="{% static '/assets/css/style.css' %}" />
        <!-- Title -->
        <title>Viet Ao Dai Boutique</title>
        <!-- Javascripts -->
        <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
    </head>
    <body>
        <!-- header -->
        <header class="header header-light header-sticky" style="background-color:#FFFFE9">
            <div class="container">
                <div class="row">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a href="{% url 'ecommerce:shop-all' %}"
                           class="navbar-brand order-1 order-lg-2">
                            <img src="{% static '/assets/images/Image.svg' %}"
                                 height="100"
                                 width="{% widthratio 175 200 100 as width %}"
                                 alt="Logo">
                        </a>
                        <button class="navbar-toggler order-2"
                                type="button"
                                data-toggle="collapse"
                                data-target=".navbar-collapse"
                                aria-controls="navbarMenu"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse order-3 order-lg-1" id="navbarMenu">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown"
                                       href="{% url 'ecommerce:shop-all' %}"
                                       id="navbarDropdown-4"
                                       role="button"
                                       data-toggle="dropdown"
                                       aria-haspopup="true"
                                       aria-expanded="false">
                                        Shop
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown-4">
                                        <ul>
                                            <li>
                                                <a class="dropdown-item" href="{% url 'ecommerce:shop-all' %}">All</a>
                                            </li>
                                            {% for item in category %}
                                                <li>
                                                    <a class="dropdown-item"
                                                       href="{% url 'ecommerce:shop-category' item.slug_url %}">{{ item.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'ecommerce:lookbook' %}">Lookbook</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:contact' %}">Contact</a>
                                </li>
                            </ul>
                        </div>
                        <div class="collapse navbar-collapse order-4 order-lg-3" id="navbarMenu2">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item dropdown">
                                    {% if request.user.is_authenticated %}
                                        <a class="nav-link dropdown text-capitalize"
                                           href="#!"
                                           id="navbarDropdown-10"
                                           role="button"
                                           data-toggle="dropdown"
                                           aria-haspopup="true"
                                           aria-expanded="false">
                                            Hi, {{ request.user.first_name|lower }} <i class="bi bi-person"></i>
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown-10">
                                            {% if request.user.is_staff %}
                                                <li>
                                                    <a class="dropdown-item " href="{% url 'account:dashboard' %}">Dashboard</a>
                                                </li>
                                            {% endif %}
                                            <li>
                                                <a class="dropdown-item " href="{% url 'account:profile' %}">Profile</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item " href="{% url 'account:orders' %}">Orders</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item text-red"
                                                   href="{% url 'account:logout' %}?next={{ request.path }}">Log Out</a>
                                            </li>
                                        </ul>
                                    {% else %}
                                        <a class="nav-link"
                                           href="{% url 'account:login' %}?next={{ request.path }}">Log In</a>
                                    {% endif %}
                                </li>
                                <li class="nav-item cart">
                                    <a href="{% url 'ecommerce:shopping-cart' %}" class="nav-link">
                                        <span class="bi bi-cart2"></span>
                                        <span id="cart-qty">{{ cart_length }}</span></a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- listing -->
        {% block shop %}{% endblock %}
        {% block cart %}{% endblock %}
        {% block product %}{% endblock %}
        {% block portal %}{% endblock %}
        {% block checkout %}{% endblock %}
        {% block lookbook %}{% endblock %}
        
        <footer class="text-gray py-0" style="background-color:#FFFFE9">
            <div class="container">
                <div class="row separated">
                    <div class="col-lg-6 py-5">
                        
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="eyebrow mb-2">Quick Links</h4>
                                <ul class="list-group list-group-columns">
                                    <li class="list-group-item">
                                        <a class="text-gray" href="{% url 'website:contact' %}">Contact Us</a>
                                    </li>
                                    <li class="list-group-item">
                                        <a class="text-gray" href="{% url 'website:contact' %}">FAQ</a>
                                    </li>
                                    <li class="list-group-item">
                                        <a class="text-gray" href="{% url 'ecommerce:lookbook' %}">Lookbook</a>
                                    </li>
                                    <li class="list-group-item">
                                        <a  class="text-gray" href="{% url 'account:terms' %}">Terms of Use</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 py-5">
                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <h4 class="eyebrow mb-2">Follow us</h4>
                                <nav class="nav nav-icons">
                                    <a class="nav-link ml-3" href="#!"><i class="bi bi-facebook"></i></a>
                                    <a class="nav-link ml-3" href="#!"><i class="bi bi-twitter"></i></a>
                                    <a class="nav-link ml-3" href="#!"><i class="bi bi-youtube"></i></a>
                                </nav>
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <p class="small">
                                    Copyrights @ Viet Ao Dai Boutique. Website By David Nguyen
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    <!-- search -->
    <script src="{% static 'vendor/js/product-filter.js' %}"></script>
    <!-- javascript -->
    <script src="{% static '/assets/js/vendor.min.js' %}"></script>
    <script src="{% static '/assets/js/app.js' %}"></script>
</body>
</html>

app/ecommerce/templates/breadcrumbs.html
{% load static %}

<section class="breadcrumbs">
    <div class="container">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="shop/">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url 'ecommerce:shop-category' 'all' %}">Shop</a></li>
              <li class="breadcrumb-item active" aria-current="all">Product Masonry</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
</section>

app/ecommerce/templates/empty-cart.html
{% extends 'base.html' %}
{% load static %}
{% block cart %}

<section class="hero">
    <div class="container" style="min-height:70vh">
        <div class="row">
            <div class="col text-left">
                <h1>Shopping Cart</h1>
            </div>        
        </div>
        <div class="row vh-md-50">
            <div class="col text-left">
                <h5>You have nothing in your shopping cart.</h5>
                <a href="{% url 'ecommerce:shop-all' %}" type="button" class="btn btn-light">Continue Shopping</a>
            </div>         
        </div>
    </div>
</section>

{% endblock %}

app/ecommerce/templates/filter.html
{% load static %}
<aside class="col-lg-3 sidebar">
    <div class="widget">
        <span class="widget-collapse d-lg-none" data-toggle="collapse" data-target="#collapse-categories" aria-expanded="false"
            aria-controls="collapse-1" role="button">
            Filter by Category
        </span>
        <div class="d-lg-block collapse" id="collapse-categories">
            <span class="widget-title">Categories</span>
            <div class="widget-content">
                <ul id="page-nav" class="nav flex-column nav-category">
                    {% for item in category %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecommerce:shop-category' item.slug_url %}" role="button">{{ item.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% for attribute in attribute %}
    {% if attribute.name in 'Price, Prices' %}
    <div class="widget">
        <span class="widget-collapse d-lg-none" data-toggle="collapse" data-target="#collapse-{{ forloop.counter }}"
            aria-expanded="false" aria-controls="collapse-{{ forloop.counter }}" role="button">
            Filter by {{ attribute.name }}
        </span>
        <div class="d-lg-block collapse" id="collapse-{{ forloop.counter }}">
            <span class="widget-title">{{ attribute.name }}</span>
            <div class="widget-content">
                <input type="text" class="rangeslider" name="Range Slider" data-min="0"
                    data-max="{{ price_filter.price__max|add:" 50" }}" data-from="0"
                    data-to="{{ price_filter.price__max|add:" 50" }}" />
            </div>
        </div>
    </div>
    {% elif attribute.name in 'Colors,Color' %}
    <div class="widget">
        <span class="widget-collapse d-lg-none" data-toggle="collapse" data-target="#collapse-{{ forloop.counter }}"
            aria-expanded="false" aria-controls="collapse-{{ forloop.counter }}" role="button">
            Filter by {{ attribute.name }}
        </span>
        <div class="d-lg-block collapse" id="collapse-{{ forloop.counter }}">
            <span class="widget-title">{{ attribute.name }}</span>
            <div class="widget-content">
                <ul class="list-unstyled">
                    {% for i in attribute_type %}
                    {% if i.parent_name == attribute.name %}
                    <li>
                        <div class="form-check form-check-color">
                            <input class="form-check-input" data-filter="{{ i.parent_name }}" type="checkbox"
                                value="{{ i.id }}" id="{{ i.id }}">
                            <label class="form-check-label" for="{{ i.id }}">
                                <span class="bg-{{ i.presentation|lower }}"></span> {{ i.name }}
                            </label>
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% else %}
    <div class="widget">
        <span class="widget-collapse d-lg-none" data-toggle="collapse" data-target="#collapse-{{ forloop.counter }}"
            aria-expanded="false" aria-controls="collapse-{{ forloop.counter }}" role="button">
            Filter by {{ attribute.name }}
        </span>
        <div class="d-lg-block collapse" id="collapse-{{ forloop.counter }}">
            <span class="widget-title">{{ attribute.name }}</span>
            <div class="widget-content">
                <ul class="list-unstyled">
                    {% for i in attribute_type %}
                    {% if i.parent_name == attribute.name %}
                    <li>
                        <div class="form-check form-check-minimal">
                            <input class="form-check-input" data-filter="{{ i.parent_name }}" value="{{ i.id }}"
                                type="checkbox" id="{{ i.id }}">
                            <label class="form-check-label" for="{{ i.id }}">{{ i.name }}</label>
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</aside>

app/ecommerce/templates/lookbook.html
{% extends 'base.html' %}
{% load static %}
{% block lookbook %}
    <!-- hero -->
    <section class="hero hero-small">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h1>Collections</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'ecommerce:shop-all'%}">Shop</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Collections</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- blog -->
    <section class="pt-0">
        <div class="container" style="min-height:60vh">
            <div class="row masonry gutter-1">
                {% for i in page_obj %}
                <div class="col-md-6 col-lg-4">
                    <article class="card card-equal card-highlight equal-150">
                        <div class="image image-"
                             style="background-image: url({{ i.images.url }})"></div>
                        <a href="{% url 'ecommerce:product-detail' i.slug %}">
                            <div class="card-header">
                                <span class="eyebrow mb-1 text-gray">{{ i.category.name }}</span>
                            </div>
                            <div class="card-footer text-right">
                                <span class="btn btn-ico btn-rounded btn-gray"><i class="bi-chevron-right"></i></span>
                            </div>
                        </a>
                    </article>
                </div>           
                {% endfor %}
            </div>
            <div class="row">
                <div class="col">
                    <ul class="pagination">
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link" href="?page={{ i }}">{{ i }} <span class="sr-only">(current)</span></a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/ecommerce/templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% block shop %}

<section class="py-15 py-xl-20" style="padding-top: 12.5rem;">
{% include 'product.html' %}
</section>

{% endblock %}